version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: steam-analytics-postgres
    environment:
      POSTGRES_DB: steam_analytics
      POSTGRES_USER: steam_user
      POSTGRES_PASSWORD: steam_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U steam_user -d steam_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - steam-network

  redis:
    image: redis:7-alpine
    container_name: steam-analytics-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - steam-network

  # Opcional: pgAdmin para gerenciar PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: steam-analytics-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@steamanalytics.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - steam-network

volumes:
  postgres_data:
  redis_data:

networks:
  steam-network:
    driver: bridge